In [ ]:
#EX 1.B NUMPY BUILDIN FUNCTIONS
#REG NO: 230701249
#STUDENT NAME: RAGAVI K
#DATE:30/07/2024

import numpy as np

num=np.random.randint(1,100,9)
print(num)

[ 4 74 33 65 22 44 45 29 74]


In [69]:
num=np.sqrt(num)
print(num)

[2.         8.60232527 5.74456265 8.06225775 4.69041576 6.63324958
 6.70820393 5.38516481 8.60232527]


In [70]:
num=num.reshape(3,3)
print(num)

[[2.         8.60232527 5.74456265]
 [8.06225775 4.69041576 6.63324958]
 [6.70820393 5.38516481 8.60232527]]


In [71]:
num.ndim

2

In [72]:
num=num.ravel()
print(num)

[2.         8.60232527 5.74456265 8.06225775 4.69041576 6.63324958
 6.70820393 5.38516481 8.60232527]


In [73]:
num.ndim

1

In [74]:
num=num.reshape(3,3)
print(num)

[[2.         8.60232527 5.74456265]
 [8.06225775 4.69041576 6.63324958]
 [6.70820393 5.38516481 8.60232527]]


In [75]:
num[1:1,1:1]

array([], shape=(0, 0), dtype=float64)

In [76]:
num[1:3,1:3]

array([[4.69041576, 6.63324958],
       [5.38516481, 8.60232527]])