In [ ]:
#EX 2 OUTLIERS DETECTION
#REG NO: 23070125949
#STUDENT NAME: RAGAVI K
#DATE:30/07/2024

import numpy as np
from scipy import stats
import seaborn as sns

num=np.random.randint(1,100,9)
print(num)

[ 9 75 97 34 45 99 21 80 91]


In [89]:
np.mean(num)

61.22222222222222

In [90]:
np.median(num)

75.0

In [91]:
stats.mode(num)

ModeResult(mode=9, count=1)

In [92]:
def out(num):
    q1=np.percentile(num,25)
    q3=np.percentile(num,75)
    iqr=q3-q1
    lb=q1-(1.5*iqr)
    ub=q3+(1.5*iqr)
    return lb,ub

In [93]:
lb,ub=out(num)
print(lb)
print(ub) #range for the non outliers

-51.5
176.5


In [96]:
new_num=num[(lb<num) & (num<ub)] #return a boolean array which satisfies the condition datas that are within the range
#num[(lb<num) & (num<ub)]  this gives the numbers that are true that is numbers thats satisfies the condition only true elemnts are returned
print(new_num)

[ 9 75 97 34 45 99 21 80 91]


In [97]:
lb1,lb2=out(new_num)
print(lb1)
print(lb2)

-51.5
176.5


In [100]:
final_num=new_num[(lb<num) & (num<ub)] 
#2 times verification
print(final_num)

[ 9 75 97 34 45 99 21 80 91]


In [103]:
print(final_num)

[ 9 75 97 34 45 99 21 80 91]
